### ISSUE TITLE
Graph tooltips out of place on FF

### ISSUE THREAD

**Issue by davezatch** [errbuddy/errbuddy#1]
Testing in Firefox 37.0, the tooltips when hovering over graph data points are placed way down the page. See screenshot:
![screenshot 2015-03-13 10 14 09](https://cloud.githubusercontent.com/assets/1193333/6635861/a24885b6-c96a-11e4-9743-163d7dc0bdfd.png)

**Comment by peh** [comment]
This issue was moved to peh/errbuddy-frontend#1
